### ISSUE TITLE
After the course is before the course --- TODO Follow up

### ISSUE THREAD

**Issue by manerotoni** [NEUBIAS/training-resources#391]
Here some points that came to my mind

- [x] How reference what software needs to be installed for executing which module and where to get the information for how to install it?
- [x] Discuss and decide on updated layout for activities/exercises see #325 
- [x] Discuss and decide on image_data organization see #331
- [ ] https://github.com/NEUBIAS/training-resources/issues/395
- [ ] Edit/create issues for things that need to be done in a respective module. 
- [ ] Shall this be one issue per task or merge issues per module?
- [ ] Update accordingly the contributing document
- [x] Set up a doodle for discussing all this

**Comment by tischi** [comment]
Also ping @lacan and @romainGuiet, who have **a lot of** experience creating great teaching material and who showed some interest in also contributing to this community resource 🥳 .

**Comment by tischi** [comment]
- [ ] https://github.com/NEUBIAS/training-resources/issues/395

**Comment by AnniekStok** [comment]
Hi @tischi, @manerotoni , @maulakhan, and @stemarcotti, @elnazfazeli

already any suggestions for a follow up meeting time? Here's a doodle if that helps: https://doodle.com/meeting/participate/id/lej7E0va

**Comment by tischi** [comment]
To be honest, I will realistically only have bandwidth for this after May 16th.

**Comment by manerotoni** [comment]
Hi @AnniekStok,
thanks for organizing it. @tischi it should not be a long meeting. 
It is really to hold on some points we learned from this round of the course and make a list of what should be done. We don't need to discuss exactly how. This could be done also online with suggestions.

**Comment by manerotoni** [comment]
Hello @AnniekStok, @tischi, @maulakhan, @stemarcotti, @elnazfazeli, and @romainGuiet, and @lecan, 
I don't think next week will work out. It is important that @tischi joins and he has no time. Also my week is getting quite busy and I would need to block the time now.

I set up a new doddle for end of may 
https://doodle.com/meeting/participate/id/b8295Ele realistic is 1.5 hours discussion time. 

See you
Antonio

**Comment by manerotoni** [comment]
Hello @AnniekStok, @tischi, @maulakhan, @stemarcotti, @elnazfazeli, and @romainGuiet, and @LECAN,
Doodle has spoken. We will talk online about the current course, improvements, and future plans: 

May 30, 2022 • 10-11 AM 

This was the only date where we got most of the participants. I apologize that some of you can't join. 

I will send a separate invitation close to the appointment.

Antonio
